name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.3"

    - name: Install uv
      run: pip install uv

    - name: Install project dependencies
      run: uv pip install --system -e .

    - name: Install dev tools (flake8 & pytest)
      run: uv pip install --system flake8 pytest

    - name: Lint with flake8
      run: |
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: uv run pytest
